# Generated by Django 2.2.5 on 2021-02-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user_id', models.CharField(max_length=20, verbose_name='user_id')),
                ('user_pw', models.CharField(max_length=20, verbose_name='user_pw')),
            ],
        ),
    ]
